### PR TITLE
Create workspace and move getters to json

### PR DESCRIPTION
**Pull request by stevenroose**
The workspace makes testing a lot easier.
F.e. the `GetTransaction` etc traits were in the client crate while the
tests for it were in the json crate, causing problems.

Eventually it seemed more logical to move these traits into the json
crate altogether.

### CODE REVIEW

**Comment by dpc** [comment]
@stevenroose So this is for addressing https://github.com/rust-bitcoin/rust-bitcoin/issues/200 ? Can't we use `Into<Transaction>` or some other trait from stdlib instead of creating our own traits like `GetTransaction`?

**Comment by dpc** [comment]
Oh. The coherence rules... Hmmmm...

I think it will not hurt to have conversion logic from the types in `json` crate. It is still potentially reusable, and the fact that result types from this crate can be easily converted to `rust-bitcoin`, `Vec<u8>`, `String` etc. is a part of the API.

**Comment by stevenroose** [comment]
Do you want me to split the PR in two parts? The thing is that the tests don't work currently because of the getters' placement.

**Comment by dpc** [comment]
My philosophy is always "iteration time trumps everything", so just don't bother about splitting patches. But I guess tests should work at least. :)

**Comment by dpc** [comment]
All fine me with me. I'm not plunning to run this on ancient debian machines. But since this is under rust-bitcoin umberalla, maybe we should consult minver of Rust with someone.

**Comment by dpc** [comment]
Let's land some stuff!

**Pull request merged**
