### PR TITLE
Update rust-bitcoin version

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@stevenroose It seems like the latest update to `proc-macro2` (brought in by serde) bumped the MSRV to 1.31 and the build for 1.24 now fails.

**Comment by stevenroose** [comment]
I'm planning a bigger update of this crate once rust-bitcoin v0.23.0 lands with the new secp version.

**Comment by thomaseizinger** [comment]
> I'm planning a bigger update of this crate once rust-bitcoin v0.23.0 lands with the new secp version.

To make the upgrade smoother for users, would you mind landing a version in-between?
There are a few things that could be addressed before doing that update all-in-once:

- decide on the MSRV or pin `serde-derive` (#84)
- bump current dependencies
- have the build on master working again

I am happy to do the actual work and send PRs if there is an agreement on _what_ we want to do :)

**Comment by stevenroose** [comment]
Can be closed with https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/86

**Pull request closed without merging**
