### PR TITLE
Bump bitcoin dependency to 0.26

### PR DESCRIPTION
**Pull request by romanz**

### CODE REVIEW

**Comment by sanket1729** [comment]
utACK 16bd0473ce440ff302da2157933c4e15cd947eeb.

**Comment by sanket1729** [comment]
For byteorder related 1.29 fix: https://github.com/rust-bitcoin/rust-bitcoin/commit/ef116ffbedb65dbf4cdcfd79b45a93c6ffb84cc6

**Review by sanket1729 — COMMENTED** [review]
For byteorder related 1.29 fix: rust-bitcoin/rust-bitcoin@ef116ff

**Comment by romanz** [comment]
> For byteorder related 1.29 fix: [rust-bitcoin/rust-bitcoin@ef116ff](https://github.com/rust-bitcoin/rust-bitcoin/commit/ef116ff)

Thanks, fixed in https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/156/commits/f0536d0041dea42b34aa55a4b1780a2bc63b5fec.

**Comment by sanket1729** [comment]
Nice, utACk f0536d0041dea42b34aa55a4b1780a2bc63b5fec

**Comment by romanz** [comment]
Tested with electrs [bump](https://github.com/romanz/electrs/compare/next...bump) branch:
https://github.com/romanz/electrs/runs/1709358609

**Review by sgeisler — CHANGES_REQUESTED** [review]
Could you just squash the commits please so we get rid of the failing one? Might help with bisecting one day.

**Comment by romanz** [comment]
Thanks, squashed :)

**Review by sanket1729 — APPROVED** [review]
reACK 965f2e56bb38e875ac61b8e12979e3fb86691def

**Review by sgeisler — APPROVED** [review]
utACK 965f2e56bb38e875ac61b8e12979e3fb86691def

**Comment by shesek** [comment]
ACK 965f2e56bb38e875ac61b8e12979e3fb86691def, tested with [bwt](https://github.com/bwt-dev/bwt).

**Comment by romanz** [comment]
Thanks!

**Comment by sgeisler** [comment]
If you need a release you have to ask @stevenroose.

**Pull request merged**
