### PR TITLE
Fix a seemingly new error in more recent Rust version

### PR DESCRIPTION
**Pull request by stevenroose**

### CODE REVIEW

**Comment by sgeisler** [comment]
Do you know if this is a regression on Rust's side or just on nightly and will probably only get relevant on stable when a new edition is released?

**Comment by elichai** [comment]
could you expand on the regression? what is failing? where? on what platform? (I'd be interested in finding/opening a rust bug if there's really a regression)

**Comment by stevenroose** [comment]
This is what I get when trying to build master with Rust v1.37:

```
$ cargo build
   Compiling bitcoincore-rpc-json v0.11.0 (/home/steven/code/rust/bitcoincore-rpc/json)
   Compiling bitcoincore-rpc v0.11.0 (/home/steven/code/rust/bitcoincore-rpc/client)
warning: trait objects without an explicit `dyn` are deprecated
  --> client/src/error.rs:97:32
   |
97 |     fn cause(&self) -> Option<&error::Error> {
   |                                ^^^^^^^^^^^^ help: use `dyn`: `dyn error::Error`
   |
   = note: #[warn(bare_trait_objects)] on by default

   Compiling integration_test v0.1.0 (/home/steven/code/rust/bitcoincore-rpc/integration_test)
error[E0008]: cannot bind by-move into a pattern guard
   --> integration_test/src/main.rs:47:46
    |
47  |             Error::JsonRpc(JsonRpcError::Rpc(e)) if e.code == -32 => {}
    |                                              ^ moves value into pattern guard
...
193 |         assert_deprecated!(cl.generate(5, None));
    |         ----------------------------------------- in this macro invocation

error[E0008]: cannot bind by-move into a pattern guard
   --> integration_test/src/main.rs:57:37
    |
57  |             Error::JsonRpc(JsonRpcError::Rpc(e)) if e.code == -32601 => {}
    |                                              ^ moves value into pattern guard
...
195 |         assert_not_found!(cl.generate(5, None));
    |         ---------------------------------------- in this macro invocation

error[E0008]: cannot bind by-move into a pattern guard
   --> integration_test/src/main.rs:57:37
    |
57  |             Error::JsonRpc(JsonRpcError::Rpc(e)) if e.code == -32601 => {}
    |                                              ^ moves value into pattern guard
...
410 |         assert_not_found!(cl.get_block_filter(&blocks[0]));
    |         --------------------------------------------------- in this macro invocation

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0008`.
error: Could not compile `integration_test`.

To learn more, run the command again with --verbose.
$ cargo --version
cargo 1.37.0 (9edd08916 2019-08-02)
```

**Comment by stevenroose** [comment]
With v1.44 it works. It might be something 1.37 specific?

**Comment by stevenroose** [comment]
Hmm, yeah it might be an accidental error (how is that possible) in a first 1.37 release that might have been fixed in 1.37.1 or so?

Anyway, this isn't harmful.

(Tried `cargo clean && cargo build` with 1.37 but still persists.)

**Comment by elichai** [comment]
Thanks, I'll look into it from the rustc side today, I wonder if this is something known or not

**Comment by elichai** [comment]
Ok, there's no bug in rustc.
What happened is that in January we allowed the MSRV tests in travis to fail https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/88 
Then in April the intergration tests were added https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/101 and they never compiled on any compiler version lower than 1.39.0.
So I think we should fix that and go back to enforcing and fixing MSRV problems (or set a new MSRV).

**Pull request merged**
