### PR TITLE
Add UnloadWalletResult

### PR DESCRIPTION
**Pull request by LimpSquid**
closes https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/290

### CODE REVIEW

**Comment by apoelstra** [comment]
Could you add some code to the integration_test crate which exercises this?

**Comment by LimpSquid** [comment]
> Could you add some code to the integration_test crate which exercises this?

Sure I'll take a look tomorrow.

**Comment by LimpSquid** [comment]
> Could you add some code to the integration_test crate which exercises this?

Amended.

**Review by apoelstra — APPROVED** [review]
utACK 0c582faa5385b1dc964ba99504deda8f89f3c6df

**Pull request merged**
