### PR TITLE
add: getrawmempool RPC verbose = true

### PR DESCRIPTION
**Pull request by 0xB10C**
This adds support for the verbose version of the getrawmempool RPC.

### CODE REVIEW

**Review by sgeisler — APPROVED** [review]
utACK f8f2ceffd0c7964a1a0ae27368cbc14c6fb61d8d

**Comment by sgeisler** [comment]
Unrelated side note: naming these responses `XyzResult` is quite confusing.

**Comment by dunxen** [comment]
utACK f8f2cef

**Review by dunxen — APPROVED** [review]

**Comment by dunxen** [comment]
Is there any interest in having this merged now? 🙂 A few of the residents' projects at qala.dev needed to patch this for verbose output.

**Review by tcharding — APPROVED** [review]
ACK f8f2ceffd0c7964a1a0ae27368cbc14c6fb61d8d

**Review by apoelstra — APPROVED** [review]
ACK f8f2ceffd0c7964a1a0ae27368cbc14c6fb61d8d

**Pull request merged**
