### PR TITLE
Release 0.14.0

### LINKED ISSUE #194: Release 0.14
There is a [RUSTSEC advisory](https://rustsec.org/advisories/RUSTSEC-2021-0078.html) for `hyper`. `rust-bitcoincore-rpc` depends on a recent version of `hyper` that is not effected by the advisory. However there has been no release since the update to `hyper` was merged [1].

Can we have a v0.14 release please so downstream users of this library can avoid the security advisory.

Thanks,
Tobin.

[1] commit: `54a427f Merge pull request #180 from Start9Labs/dependencies/jsonrpc`

### PR DESCRIPTION
**Pull request by Tibo-lg**
Closes #194 

Updated changelog and version, hope I didn't forget anything and that it's helpful.

Cherry picked commit from #188

### CODE REVIEW

**Comment by sanket1729** [comment]
@sgeisler, @stevenroose can we have please release with 0.27 types?

**Review by sgeisler — APPROVED** [review]
ACK 679230cdf8e06edf5114eb1146a206ac7b11e42e

**Comment by stevenroose** [comment]
I noticed that my MSRV test broke. I can create a followup MR to fix that in the README.
ACK 679230c

**Comment by romanz** [comment]
Would it be possible to create a new release on https://crates.io/crates/bitcoincore-rpc?

**Comment by romanz** [comment]
[Thanks](https://crates.io/crates/bitcoincore-rpc/0.14.0)!

**Pull request merged**
