### PR TITLE
Bump crate version to `v0.17.0`

### PR DESCRIPTION
**Pull request by tcharding**
Add release notes and increase the crate minor version to 0.17.0

Justified because we just bumped the `rust-jsonrpc` minor version.

- Patch 1 updates `rust-jsonrpc` dependency to current version
- Patch 2 does the release

### CODE REVIEW

**Comment by Kixunil** [comment]
Looks like this crate needs more love... :(

**Comment by romanz** [comment]
Ping @stevenroose :)

**Comment by schildbach** [comment]
Any plans on merging this? IPv6 support is needed in the projects downstream.

**Comment by apoelstra** [comment]
@tcharding can you bump the rust-jsonrpc version to 0.14.0

**Comment by tcharding** [comment]
Sure can, no sweat.

**Comment by tcharding** [comment]
I've removed what was patch 1 of this PR, which while valid, displayed a lack of understanding of how `cargo` resolves dependencies and is basically unnecessary :) `rust-bitcoin` latest version _is_ 0.29.0 and `cargo` will build with the latest point release `0.29.2` - face palm.

**Comment by tcharding** [comment]
@stevenroose can you release this please bro? @apoelstra do you have perms to do the release if Steven doesn't get to it?

**Comment by apoelstra** [comment]
It looks like no, I do not.

**Comment by benma** [comment]
@stevenroose please also include this in the 0.17.0 release:

https://github.com/rust-bitcoin/rust-bitcoincore-rpc/commit/6c4cd8a05981a0ae6b8478ce76eb56032d40392f

Also, when release? :smile:

**Review by w0xlt — APPROVED** [review]
ACK https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/253/commits/37786d3857d4d3bdb9cccd2c0b36cbb785fddef8

**Comment by stevenroose** [comment]
Sorry for my inactivity lately! I'll merge and release this right now :)

**Comment by Kixunil** [comment]
Would you please consider adding someone as a co-maintainer so that releases are not blocked by your time?

**Pull request merged**
