### PR TITLE
 Impl `send_to_address` 

### PR DESCRIPTION
**Pull request by dpc**
On top of previous changes.

### CODE REVIEW

**Comment by stevenroose** [comment]
It looks like this one is again introducing the `create_raw_transaction` methods somehow. Could you rebase this again? I think we can merge it tomorrow then.

**Comment by stevenroose** [comment]
The return type of that is a txid. Could you make it return a `Sha256dHash` instead of a `String` then?

**Comment by stevenroose** [comment]
You should be able to just change the return type because `call` does automatic convertion.

**Comment by stevenroose** [comment]
I'll just merge it and edit it.

**Comment by dpc** [comment]
Awesome. Thank you.

**Pull request merged**
