### PR TITLE
Release tracking PR:  `v0.19.0`

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for release add a changelog entry and bump the version number.

Patch 1 is a trivial cleanup of an old stale changelog file, no longer used.

### CODE REVIEW

**Comment by tcharding** [comment]
All PRs ready to merge, lets get this release out!

**Comment by tcharding** [comment]
Don't merge yet!

**Comment by tcharding** [comment]
ok, looks good now. I did: 

- `cargo publish -p bitcoincore-rpc-json --dry-run` and that succeeds
- `cargo publish -p bitcoincore-rpc --dry-run` fails because the `bitcoincore-rpc-json` crate doesn't exist (yet).

**Comment by tcharding** [comment]
If you merge @apoelstra I'll tag and publish both crates.

**Review by apoelstra — APPROVED** [review]
ACK 839fcb6dc0fa5a2361c0bab257ed60af4c256540

**Comment by apoelstra** [comment]
Ok, merged. Go for it!

**Comment by tcharding** [comment]
Damn, damn, damn, damn, damn - I've only got publish perms on `bitcoincore-rpc` on on `bitcoincore-rpc-json`.

CC @stevenroose

**Comment by tcharding** [comment]
Further explanation: Steven gave me perms on one crate so I could publish but we forgot the other, `bitcoincore-rpc` release requires a release of `bitocincore-rpc-json` first.

**Pull request merged**
