### PR TITLE
Add getbalance

### PR DESCRIPTION
**Pull request by stevenroose**
Blocked on rust-bitcoin v0.19: https://github.com/rust-bitcoin/rust-bitcoin/milestone/7

Fixes https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/72.

@ciyool could you test if this works for you?

### CODE REVIEW

**Comment by ciyool** [comment]
> Fixes #72.
> 
> @ciyool could you test if this works for you?

I tested and got the result:
``` rust
rust code:
let info=client.get_balance(Some(6),Some(false));
println!("get_balance: {:?}",info);

result:
JSON-RPC request: {"method":"getbalance","params":["*",6,false],"id":3,"jsonrpc":"2.0"}
JSON-RPC response: {"result":0.13005387,"error":null,"id":3,"jsonrpc":null}
get_balance: Err(JsonRpc(Json(Error("invalid type: floating point `0.13005387`, expected i64", line: 0, column: 0))))
```

**Comment by stevenroose** [comment]
Ah, right. Let's wait until rust-bitcoin v0.19 lands which has a stable `Amount` type that can handle floats correctly.

**Comment by stevenroose** [comment]
@ciyool could you test again? I updated it.

**Comment by stevenroose** [comment]
I'm gonna merge it for a release candidate.

**Pull request merged**
