### PR TITLE
Bump 'bitcoin' crate to 0.28.0

### PR DESCRIPTION
**Pull request by romanz**
Following https://github.com/rust-bitcoin/rust-bitcoin/pull/789.

### CODE REVIEW

**Comment by romanz** [comment]
See https://github.com/romanz/electrs/commit/1fe9104ad8f44478d1cf07c33d5c0b694530370c.

**Comment by romanz** [comment]
Updated for `bitcoin` 0.28.0 (following https://github.com/rust-bitcoin/rust-bitcoin/pull/944)

**Review by elichai — APPROVED** [review]
ACK e35368f217d7934d6d7427eade25d282e3831465

**Comment by sanket1729** [comment]
ACK e35368f217d7934d6d7427eade25d282e3831465

**Review by dunxen — APPROVED** [review]
ACK e35368f

**Review by RCasatta — APPROVED** [review]
ACK e35368f217d7934d6d7427eade25d282e3831465

**Comment by romanz** [comment]
Many thanks!

**Pull request merged**
