### PR TITLE
Change getblockchaininfo softfork format

### PR DESCRIPTION
**Pull request by stevenroose**
This apparently changed in Core in current master.

Blocked because not released yet in Core.

### CODE REVIEW

**Comment by fodder1997** [comment]
Hello,

I was wondering if there was any movement on this? I've inherited a rust project (I don't know rust) that uses this lib and pretty sure its breaking on parsing the results from getblockchaininfo. We're running bitcoin core node 0.19.0.1.

Thanks

**Comment by fodder1997** [comment]
Hi - Thanks for this. 

Is there a release coming or can I get on a nightly build? 

I tried to grab the latest through git by updating my `Cargo.toml`. I added `bitcoincore-rpc = { git = "https://github.com/rust-bitcoin/rust-bitcoincore-rpc" }` but I'm getting errors around `error: failed to select a version for cc` so suspect I may be doing something wrong.

(Feel free to ignore me here as I appreciate running open source project is a thankless task and you don't need to be doing support to newbies.)

thanks again

**Comment by stevenroose** [comment]
Strange. Try doing `cargo update cc` or something. I can build this succesfully, but we had problems with breaking cc changes several times in the rust-bitcoin crates. Some might have `<` constraints because of breaking changes.

**Comment by stevenroose** [comment]
This is published to crates.io as well, fwiw.

**Pull request merged**
