### PR TITLE
Support 'witness_v1_taproot' in ScriptPubkeyType enum

### PR DESCRIPTION
**Pull request by romanz**
Should fix https://github.com/romanz/electrs/issues/427.

### CODE REVIEW

**Comment by shesek** [comment]
ACK 1ea3dbe944fc7780c72c2b6160a96bd49f1a9cac

**Comment by 0xB10C** [comment]
ACK 1ea3dbe944fc7780c72c2b6160a96bd49f1a9cac

**Comment by elichai** [comment]
utACK 1ea3dbe944fc7780c72c2b6160a96bd49f1a9cac

Source: https://github.com/bitcoin/bitcoin/blob/6499928bfb19674f98724b4aa5238d874e6738e4/src/script/standard.cpp#L49-L64

Do we want to add a witness_unknown one? or some `Other` variant with a string? (I'd combine this with non_exhuastive maybe, but can't think exactly how in a nice way)

**Comment by romanz** [comment]
Thanks!

> Do we want to add a `witness_unknown` one?

IIUC, it should be supported by the current code:
https://github.com/rust-bitcoin/rust-bitcoincore-rpc/blob/54a427f2e45b0b8712d44a6995f6a03ad5f961f8/json/src/lib.rs#L631

**Comment by romanz** [comment]
Ping :)

**Comment by romanz** [comment]
Ping :)

**Review by RCasatta — APPROVED** [review]
utACK 1ea3dbe

**Pull request merged**
