### PR TITLE
Add Bitcoin Core 0.20.0 to Travis

### PR DESCRIPTION
**Pull request by justinmoon**

### CODE REVIEW

**Comment by justinmoon** [comment]
Am I supposed to see Travis run here?

**Comment by stevenroose** [comment]
Yeah, so it looks broken. That happens sometimes of either Travis or GitHub is under heavy load. I think the best you can do is re-push. Also, you'll probably have to fix a bunch of stuff to make this test pass ;)

**Comment by stevenroose** [comment]
Somehow Travis didn't built any PR past #122.. https://travis-ci.org/github/rust-bitcoin/rust-bitcoincore-rpc/pull_requests

**Comment by justinmoon** [comment]
What do you mean "re-push". Just pushed another commit and Travis still seems to be asleep.

**Comment by sgeisler** [comment]
Is your or the org's account rate limited/disabled? It happened to me once for running bitcoind in regtest mode because they thought I was mining.

**Comment by stevenroose** [comment]
Superceded by https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/139.

**Pull request closed without merging**
